### PR TITLE
pair_generatio_circ

### PR DESCRIPTION
**Pull request by SakibulIslamSazzad**
pair generation circuit in cirq

### CODE REVIEW

**Comment by gravityshouldbenaut** [comment]
Did you want to also include @johnzl-777 's circuit within this notebook?

**Comment by SakibulIslamSazzad** [comment]
yes I wanted but got confused with, which section should be added. I will try to do that later. Currently focusing on the optimiser.

**Comment by gravityshouldbenaut** [comment]
Ah okay, its the iswap found here, as that iswap is what got the Givens https://github.com/QC-at-Davis/ProFold/blob/feature/vectoradditionfrombiomoleculesusingbiopython/src/scripts/IonQ-Givens-Cost-Estimation.ipynb

**Comment by gravityshouldbenaut** [comment]
Also, can you make it fit for 8 qubits? So, double what you currently have? That way it fits the paper model.
image

**Pull request merged**
